# Generated by Django 3.2.2 on 2021-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(choices=[('мл', 'мл'), ('г', 'щепотку'), ('г', 'ч.л.'), ('г', 'ст.л.'), ('г', 'г'), ('г', 'по вкусу')], max_length=126),
        ),
    ]
