# Generated by Django 3.2.2 on 2021-05-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210511_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipes',
            name='favor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='recipes.recipe'),
        ),
    ]
