# Generated by Django 3.2.2 on 2021-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210520_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название тега')),
                ('display_name', models.CharField(max_length=50, verbose_name='Название тега для шаблона')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет тега')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag_breakfast',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag_dinner',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag_lunch',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag', verbose_name='Теги'),
        ),
    ]
